name: Generate Podcast Feed

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Feed Generator
        uses: your-username/podcastgenerator@main  # Replace 'your-username' with your GitHub username
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
        
